# Generated by Django 4.2.3 on 2024-01-01 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reg.models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', reg.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='EbcCreated_at',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='buyPrice',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='购买价格'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fanHuan',
            field=models.DecimalField(blank=True, db_comment='可以返还用户B数量', decimal_places=4, max_digits=10, null=True, verbose_name='可以返还用户B数量'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.IntegerField(choices=[(0, '未生效'), (1, '已生效')], db_comment='0 未生效,1已生效:反润生效', default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userStakesA',
            field=models.BigIntegerField(blank=True, db_comment='用户质押A数量', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userStakesB',
            field=models.BigIntegerField(blank=True, db_comment='用户质押B数量', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userStakesBfanHuan',
            field=models.DecimalField(blank=True, db_comment='返还用户B数量', decimal_places=4, max_digits=10, null=True, verbose_name='返还用户B数量'),
        ),
        migrations.CreateModel(
            name='ebcZhiYa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userStakesA', models.BigIntegerField(blank=True, db_comment='用户质押A数量', null=True)),
                ('userStakesB', models.BigIntegerField(blank=True, db_comment='用户质押B数量', null=True)),
                ('userStakesBfanHuan', models.DecimalField(blank=True, db_comment='返还用户B数量', decimal_places=4, max_digits=10, null=True, verbose_name='返还用户B数量')),
                ('fanHuan', models.DecimalField(blank=True, db_comment='可以返还用户B数量', decimal_places=4, max_digits=10, null=True, verbose_name='可以返还用户B数量')),
                ('status', models.IntegerField(choices=[(0, '未生效'), (1, '已生效')], db_comment='0 未生效,1已生效', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('Remark', models.CharField(blank=True, db_comment='task备注', max_length=255, null=True, verbose_name='备注')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '加速收益记录',
                'db_table': 't_ebcZhiYa',
                'db_table_comment': '加速收益记录',
            },
        ),
        migrations.CreateModel(
            name='ebcJiaSuShouYiJiLu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskId', models.CharField(blank=True, db_comment='taskId', max_length=255, null=True, verbose_name='taskId')),
                ('uidA', models.BigIntegerField(blank=True, db_comment='用户A-发送方', null=True)),
                ('uidB', models.BigIntegerField(blank=True, db_comment='用户B-接收方', null=True)),
                ('status', models.IntegerField(choices=[(0, '未生效'), (1, '已生效')], db_comment='0 未生效,1已生效:反润生效', default=0)),
                ('EbcCreated_at', models.BigIntegerField(blank=True, null=True, verbose_name='创建时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('Remark', models.CharField(blank=True, db_comment='task备注', max_length=255, null=True, verbose_name='备注')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '加速收益记录',
                'db_table': 't_ebcJiaSuShouYiJiLu',
                'db_table_comment': '加速收益记录',
            },
        ),
    ]
