# Generated by Django 4.2.3 on 2024-01-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0003_remove_ebcjiasushouyijilu_ebccreated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='buyPrice',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fanHuan',
            field=models.DecimalField(blank=True, db_comment='可以返还用户B数量', decimal_places=4, max_digits=30, null=True, verbose_name='可以返还用户B数量'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userStakesBfanHuan',
            field=models.DecimalField(blank=True, db_comment='返还用户B数量', decimal_places=4, max_digits=30, null=True, verbose_name='返还用户B数量'),
        ),
    ]
