# Generated by Django 4.2.3 on 2024-01-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0008_alter_customuser_userstakesa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fanHuan',
            field=models.FloatField(blank=True, db_comment='可以返还用户B数量', default=0, null=True, verbose_name='可以返还用户B数量'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userStakesA',
            field=models.FloatField(blank=True, db_comment='用户质押A数量', default=0, null=True, verbose_name='用户质押A数量'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userStakesB',
            field=models.FloatField(blank=True, db_comment='用户质押B数量', default=0, null=True, verbose_name='用户质押B数量'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userStakesBfanHuan',
            field=models.FloatField(blank=True, db_comment='返还用户B数量', default=0, null=True, verbose_name='返还用户B数量'),
        ),
        migrations.AlterField(
            model_name='ebcjiasushouyijilu',
            name='fanHuan',
            field=models.FloatField(blank=True, db_comment='每次返还额度', default=0, null=True, verbose_name='每次返还额度'),
        ),
        migrations.AlterField(
            model_name='ebcjiasushouyijilu',
            name='uidA',
            field=models.FloatField(blank=True, db_comment='用户A-发送方', default=0.0, null=True, verbose_name='用户A-发送方'),
        ),
        migrations.AlterField(
            model_name='ebcjiasushouyijilu',
            name='uidB',
            field=models.FloatField(blank=True, db_comment='用户B-接收方', default=0, null=True, verbose_name='用户B-接收方'),
        ),
        migrations.AlterField(
            model_name='ebczhiya',
            name='fanHuan',
            field=models.FloatField(blank=True, db_comment='可以返还用户B数量', null=True, verbose_name='可以返还用户B数量'),
        ),
        migrations.AlterField(
            model_name='ebczhiya',
            name='userStakesBfanHuan',
            field=models.FloatField(blank=True, db_comment='返还用户B数量', null=True, verbose_name='返还用户B数量'),
        ),
    ]
