# Generated by Django 4.2.3 on 2024-01-09 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0010_ebcjiasushouyijilu_layer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebcjiasushouyijilu',
            name='uid',
        ),
    ]
