# Generated by Django 4.2.3 on 2024-01-09 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0012_remove_ebcjiasushouyijilu_leixing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tokenZhiYaJiShi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokenName', models.CharField(blank=True, db_comment='质押名称', max_length=255, null=True, verbose_name='质押名称')),
                ('number', models.FloatField(blank=True, db_comment='质押数量', null=True, verbose_name='质押数量')),
                ('zhiYaTime', models.BigIntegerField(blank=True, db_comment='质押100天', null=True)),
                ('kaiShiTime', models.BigIntegerField(blank=True, null=True, verbose_name='开始质押时间')),
                ('status', models.IntegerField(choices=[(0, '质押中'), (1, '已释放')], db_comment='0 质押中,已释放', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('Remark', models.CharField(blank=True, db_comment='task备注', max_length=255, null=True, verbose_name='备注')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '质押代币时间',
                'db_table': 't_ymiiZhiYaJiShi',
                'db_table_comment': '质押代币时间',
            },
        ),
    ]
