# Generated by Django 4.2.3 on 2024-01-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0013_tokenzhiyajishi'),
    ]

    operations = [
        migrations.CreateModel(
            name='payToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uidA', models.IntegerField(blank=True, db_comment='用户A-发送方', default=0, null=True, verbose_name='用户A-发送方')),
                ('uidB', models.IntegerField(blank=True, db_comment='用户B-接收方', default=0, null=True, verbose_name='用户B-接收方')),
                ('status', models.IntegerField(choices=[(0, '未生效'), (1, '已生效')], db_comment='0 未生效,1已生效:反润生效', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('amount', models.FloatField(blank=True, db_comment='每次返还额度', default=0, null=True, verbose_name='每次返还额度')),
                ('liuShuiId', models.IntegerField(blank=True, db_comment='流水ID 合约同步', default=0, null=True)),
                ('Remark', models.CharField(blank=True, db_comment='task备注', max_length=255, null=True, verbose_name='备注')),
                ('Layer', models.IntegerField(blank=True, db_comment='0提现', default=0, null=True, verbose_name='类型')),
                ('tiXianWallter', models.CharField(blank=True, db_comment='提现钱包', max_length=255, null=True, verbose_name='提现钱包')),
                ('TxHash', models.CharField(blank=True, db_comment='交易hash', max_length=255, null=True, verbose_name='交易hash')),
                ('tiBiADDRESS', models.CharField(blank=True, db_comment='提取代币地址', max_length=255, null=True, verbose_name='提取代币地址')),
                ('AdminUser', models.IntegerField(blank=True, db_comment='管理账号ID', default=0, null=True, verbose_name='管理账号ID')),
            ],
            options={
                'verbose_name_plural': '支付流水',
                'db_table': 't_payToken',
                'db_table_comment': '支付流水',
            },
        ),
        migrations.AlterField(
            model_name='ebcjiasushouyijilu',
            name='Layer',
            field=models.IntegerField(blank=True, db_comment='0充值1代数范润2层级范润3平台日返1.5%,4提现', default=0, null=True, verbose_name='类型'),
        ),
    ]
