# Generated by Django 4.2.3 on 2024-01-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0014_paytoken_alter_ebcjiasushouyijilu_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='paytoken',
            name='hashInfo',
            field=models.CharField(blank=True, db_comment='hash信息', max_length=255, null=True, verbose_name='hash信息'),
        ),
    ]
