# Generated by Django 4.2.3 on 2024-03-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0015_paytoken_hashinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='kapaiLevel',
            field=models.IntegerField(blank=True, db_comment='0 买A卡,1买B卡 2 买C卡', default=0, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tuanduiLevel',
            field=models.IntegerField(blank=True, db_comment='团队等级', default=0, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userLevel',
            field=models.IntegerField(blank=True, db_comment='用户等级', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.IntegerField(choices=[(0, '未生效'), (1, '已生效')], db_comment='0 未生效,1已生效:不可购买矿机', default=0),
        ),
        migrations.AlterField(
            model_name='paytoken',
            name='status',
            field=models.IntegerField(choices=[(0, '未生效'), (1, '返回hash'), (2, 'hash验证失败'), (3, 'hash验证成功')], db_comment='0 未生效,1,返回hash ,2 hash验证失败,3hash验证成功', default=0),
        ),
    ]
