# Generated by Django 4.2.3 on 2024-03-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0016_customuser_kapailevel_customuser_tuanduilevel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='kapaiA',
            field=models.IntegerField(blank=True, db_comment='A卡数量', default=0, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kapaiB',
            field=models.IntegerField(blank=True, db_comment='B卡卡数量', default=0, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kapaiC',
            field=models.IntegerField(blank=True, db_comment='C卡卡数量', default=0, null=True),
        ),
    ]
