# Generated by Django 4.2.3 on 2024-04-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0017_customuser_kapaia_customuser_kapaib_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenzhiyajishi',
            name='layer',
            field=models.IntegerField(choices=[(0, '质押中'), (1, '已释放')], db_comment='0 矿机质押,1 日加速', default=0),
        ),
    ]
