# Generated by Django 4.2.3 on 2024-04-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0018_tokenzhiyajishi_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebcjiasushouyijilu',
            name='tokenZhiYaJiShiId',
            field=models.IntegerField(blank=True, db_comment='质押表ID', default=0, null=True),
        ),
    ]
