# Generated by Django 4.2.3 on 2024-04-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0019_ebcjiasushouyijilu_tokenzhiyajishiid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebcjiasushouyijilu',
            name='Layer',
            field=models.IntegerField(blank=True, db_comment='0矿机 1 卡牌  ', default=0, null=True, verbose_name='类型'),
        ),
    ]
