# Generated by Django 4.2.3 on 2024-04-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0020_alter_ebcjiasushouyijilu_layer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebcjiasushouyijilu',
            name='Layer',
            field=models.IntegerField(blank=True, db_comment='0充值 1 代数 2 层数 3 #提现到账 日志   ', default=0, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='tokenzhiyajishi',
            name='layer',
            field=models.IntegerField(choices=[(0, '质押中'), (1, '已释放')], db_comment='0 矿机质押,1日返利 其他非零 是卡牌 ', default=0),
        ),
    ]
