# Generated by Django 4.2.3 on 2024-06-06 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0021_alter_ebcjiasushouyijilu_layer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(blank=True, db_comment='用户', default=0, null=True)),
                ('status', models.IntegerField(choices=[(0, '未生效'), (1, '已生效')], db_comment='0 未生效,1已生效:反润生效', default=0)),
                ('cTime', models.BigIntegerField(blank=True, db_comment='操作时间', default=0, null=True)),
                ('uTime', models.BigIntegerField(blank=True, db_comment='更新时间', default=0, null=True)),
                ('amount', models.FloatField(blank=True, db_comment='购买价格', default=0, null=True, verbose_name='购买价格')),
                ('lianShangId', models.IntegerField(blank=True, db_comment='链上ID 合约同步', default=0, null=True)),
                ('NodeName', models.CharField(blank=True, db_comment='购买矿机名称', max_length=255, null=True, verbose_name='购买矿机名称')),
                ('Remark', models.CharField(blank=True, db_comment='task备注', max_length=255, null=True, verbose_name='备注')),
                ('Layer', models.IntegerField(blank=True, db_comment='0节点矿机', default=0, null=True, verbose_name='类型')),
            ],
            options={
                'verbose_name_plural': '购买节点矿机',
                'db_table': 't_buyNode',
                'db_table_comment': '购买节点矿机',
            },
        ),
        migrations.CreateModel(
            name='userToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '未生效'), (1, '已生效')], db_comment='0 未生效,1已生效', default=0)),
                ('cTime', models.IntegerField(blank=True, db_comment='操作时间', default=0, null=True)),
                ('uTime', models.IntegerField(blank=True, db_comment='更新时间', default=0, null=True)),
                ('usdtToken', models.FloatField(blank=True, db_comment='usdtToken', default=0, null=True, verbose_name='usdtToken')),
                ('ylToken', models.FloatField(blank=True, db_comment='ylToken', default=0, null=True, verbose_name='ylToken')),
                ('jzToken', models.FloatField(blank=True, db_comment='jzToken', default=0, null=True, verbose_name='jzToken')),
                ('oneToken', models.FloatField(blank=True, db_comment='oneToken', default=0, null=True, verbose_name='oneToken')),
                ('towToken', models.FloatField(blank=True, db_comment='towToken', default=0, null=True, verbose_name='towToken')),
                ('Remark', models.CharField(blank=True, db_comment='task备注', max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '用户Token',
                'db_table': 't_userToken',
                'db_table_comment': '用户Token',
            },
        ),
        migrations.RemoveField(
            model_name='tokenzhiyajishi',
            name='layer',
        ),
        migrations.AddField(
            model_name='customuser',
            name='cengShu',
            field=models.IntegerField(blank=True, db_comment='当前矿机code', default=0, null=True),
        ),
        migrations.AddField(
            model_name='ebcjiasushouyijilu',
            name='cTime',
            field=models.BigIntegerField(blank=True, db_comment='操作时间', default=0, null=True),
        ),
        migrations.AddField(
            model_name='tokenzhiyajishi',
            name='amount',
            field=models.FloatField(blank=True, db_comment='质押额度', null=True, verbose_name='质押额度'),
        ),
        migrations.AddField(
            model_name='tokenzhiyajishi',
            name='amountType',
            field=models.CharField(blank=True, db_comment='质押类型', max_length=255, null=True, verbose_name='质押类型'),
        ),
        migrations.AddField(
            model_name='tokenzhiyajishi',
            name='nodeKjCode',
            field=models.IntegerField(blank=True, db_comment='矿机Code', default=0, null=True, verbose_name='矿机Code'),
        ),
        migrations.AddField(
            model_name='tokenzhiyajishi',
            name='uTime',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='更新时间'),
        ),
        migrations.DeleteModel(
            name='ebcZhiYa',
        ),
        migrations.AddField(
            model_name='usertoken',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tokenzhiyajishi',
            name='Layer',
            field=models.IntegerField(blank=True, db_comment='0 矿机质押,1日返利 其他非零 是卡牌  ', default=0, null=True, verbose_name='类型'),
        ),
    ]
