# Generated by Django 4.2.3 on 2024-06-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0022_buynode_usertoken_remove_tokenzhiyajishi_layer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paytoken',
            name='HashId',
            field=models.CharField(blank=True, db_comment='唯一hashId', max_length=255, null=True, verbose_name='唯一hashId'),
        ),
    ]
