# Generated by Django 4.2.3 on 2024-06-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0023_paytoken_hashid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='zhiTuiNum',
            field=models.IntegerField(blank=True, db_comment='暂存直推人数', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ebcjiasushouyijilu',
            name='Layer',
            field=models.IntegerField(blank=True, db_comment='0充值 1 代数 2 层数 3 #提现到账 日志 4.购买燃料包  ', default=0, null=True, verbose_name='类型'),
        ),
    ]
