# Generated by Django 4.2.3 on 2024-06-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0024_customuser_zhituinum_alter_ebcjiasushouyijilu_layer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cengShu',
            field=models.IntegerField(blank=True, db_comment='当前矿机code', default=1, null=True),
        ),
    ]
