# Generated by Django 4.2.3 on 2024-06-11 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0025_alter_customuser_cengshu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paytoken',
            options={'verbose_name_plural': '提现流水'},
        ),
        migrations.AlterModelTableComment(
            name='paytoken',
            table_comment='提现流水',
        ),
    ]
