# Generated by Django 4.2.3 on 2024-06-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0026_alter_paytoken_options_alter_paytoken_table_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebcjiasushouyijilu',
            name='Layer',
            field=models.IntegerField(blank=True, db_comment='0充值 1 代数 2 层数 3 #提现到账 日志 4.购买燃料包  11.得到奖金池', default=0, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='paytoken',
            name='status',
            field=models.IntegerField(choices=[(0, '未生效'), (1, '返还'), (2, 'hash验证失败'), (3, 'hash验证成功')], db_comment='0 未生效,1,返回hash ,2 hash验证失败,3hash验证成功', default=0),
        ),
    ]
