# Generated by Django 4.2.3 on 2024-07-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0028_tokenzhiyajishi_amountshouyi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebcjiasushouyijilu',
            name='hash',
            field=models.CharField(blank=True, db_comment='链上hash', max_length=255, null=True, verbose_name='链上hash'),
        ),
    ]
