# Generated by Django 4.2.3 on 2023-08-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TcSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(blank=True, db_comment='用户ID', null=True)),
                ('noStr', models.CharField(blank=True, db_comment='TcSports编号str', max_length=255, null=True)),
                ('noInt', models.IntegerField(blank=True, db_comment='TcSports编号int', null=True)),
                ('name', models.CharField(db_comment='名称', max_length=50)),
                ('status', models.IntegerField(db_comment='0 未开,1开', default=1)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('webid', models.IntegerField(blank=True, db_comment='站点id', default=0, null=True)),
                ('cn_memo', models.CharField(blank=True, db_comment='中文备注', max_length=200, null=True)),
            ],
            options={
                'db_table': 'TcSports',
                'db_table_comment': 'TcSports各种运动信息',
            },
        ),
        migrations.CreateModel(
            name='TcWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(blank=True, db_comment='用户ID', null=True)),
                ('noStr', models.CharField(blank=True, db_comment='tcWeb编号str', max_length=255, null=True)),
                ('noInt', models.IntegerField(blank=True, db_comment='tcWeb编号int', null=True)),
                ('name', models.CharField(db_comment='名称', max_length=50)),
                ('status', models.IntegerField(db_comment='0 为开,1开', default=1)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('webid', models.IntegerField(blank=True, db_comment='站点id', default=0, null=True)),
                ('cn_memo', models.CharField(blank=True, db_comment='中文备注', max_length=200, null=True)),
            ],
            options={
                'db_table': 'TcWeb',
                'db_table_comment': 'tcWeb各种站点信息',
            },
        ),
        migrations.CreateModel(
            name='TcSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(blank=True, db_comment='用户ID', null=True)),
                ('paiXu', models.CharField(blank=True, db_comment='tcWeb编号str', max_length=255, null=True)),
                ('menOneTwo', models.CharField(blank=True, db_comment='tcWeb编号str', max_length=255, null=True)),
                ('profitRangeLittle', models.CharField(blank=True, db_comment='利润范围最小值', default=0, max_length=255, null=True)),
                ('profitRangeBig', models.CharField(blank=True, db_comment='利润范围最大值', default=0, max_length=255, null=True)),
                ('returnOnInvestmentLittle', models.CharField(blank=True, db_comment='投资汇报率最小值', default=0, max_length=255, null=True)),
                ('returnOnInvestmentBig', models.CharField(blank=True, db_comment='投资汇报率最大值', max_length=255, null=True)),
                ('raceTime', models.IntegerField(blank=True, db_comment='raceTime比赛时间', default=0, null=True)),
                ('moreSearch', models.CharField(blank=True, db_comment='高级选项-多选内容', max_length=50, null=True)),
                ('status', models.IntegerField(db_comment='0 未开,1开', default=1)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('webid', models.IntegerField(blank=True, db_comment='站点id', default=0, null=True)),
                ('cn_memo', models.CharField(blank=True, db_comment='中文备注', max_length=200, null=True)),
                ('gender', models.SmallIntegerField(blank=True, choices=[(2, '女'), (1, '男')], null=True, verbose_name='性别')),
                ('tcSports', models.ManyToManyField(to='app1.tcsport')),
                ('tcWebs', models.ManyToManyField(to='app1.tcweb')),
            ],
            options={
                'db_table': 'TcSearch',
                'db_table_comment': 'TcSearch个人搜索条件',
            },
        ),
    ]
