# Generated by Django 4.2.3 on 2023-08-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcsearch',
            name='tcSports',
            field=models.ManyToManyField(blank=True, null=True, to='app1.tcsport'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='tcWebs',
            field=models.ManyToManyField(blank=True, null=True, to='app1.tcweb'),
        ),
    ]
