# Generated by Django 4.2.3 on 2023-08-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_tcsearch_tcsports_alter_tcsearch_tcwebs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tcweb',
            options={'verbose_name': 'tc网站', 'verbose_name_plural': 'tc网站plural'},
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(2, '女'), (1, '男')], default=1, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='tcSports',
            field=models.ManyToManyField(to='app1.tcsport'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='tcWebs',
            field=models.ManyToManyField(to='app1.tcweb'),
        ),
    ]
