# Generated by Django 4.2.3 on 2023-08-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_tcsearch_gender_alter_tcsearch_paixu'),
    ]

    operations = [
        migrations.CreateModel(
            name='TcOneTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(blank=True, db_comment='用户ID', null=True)),
                ('noStr', models.CharField(blank=True, db_comment='TcOneTwo编号str', max_length=255, null=True)),
                ('noInt', models.IntegerField(blank=True, db_comment='TcOneTwo编号int', null=True)),
                ('name', models.CharField(db_comment='名称', max_length=50)),
                ('status', models.IntegerField(db_comment='0 为开,1开', default=1)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('webid', models.IntegerField(blank=True, db_comment='站点id', default=0, null=True)),
                ('cn_memo', models.CharField(blank=True, db_comment='中文备注', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'TcOneTwo两门三门',
                'verbose_name_plural': '两门三门plural',
                'db_table': 'TcOneTwo',
                'db_table_comment': 'TcOneTwo各种站点信息',
            },
        ),
        migrations.RemoveField(
            model_name='tcsearch',
            name='menOneTwo',
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='paiXu',
            field=models.SmallIntegerField(blank=True, choices=[(4, 'ROI'), (1, '存在时间'), (3, '利润'), (2, '开始时间')], default=1, null=True, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='tcsearch',
            name='menOneTwo',
            field=models.ManyToManyField(to='app1.tconetwo'),
        ),
    ]
