# Generated by Django 4.2.3 on 2023-08-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_tconetwo_remove_tcsearch_menonetwo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tcsearch',
            old_name='menOneTwo',
            new_name='menOneTwos',
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(2, '女'), (1, '男')], default=1, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='paiXu',
            field=models.SmallIntegerField(blank=True, choices=[(3, '利润'), (2, '开始时间'), (1, '存在时间'), (4, 'ROI')], default=1, null=True, verbose_name='排序'),
        ),
    ]
