# Generated by Django 4.2.3 on 2023-08-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_tcsearch_paixu_alter_tcsearch_racetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcsearch',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(1, '男'), (2, '女')], default=1, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='paiXu',
            field=models.SmallIntegerField(blank=True, choices=[(3, '利润'), (2, '开始时间'), (1, '存在时间'), (4, 'ROI')], default=1, null=True, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='raceTime',
            field=models.SmallIntegerField(blank=True, choices=[(6, '1周'), (5, '2天'), (3, '16小时'), (1, '任何时间'), (7, '4周2天'), (4, '1天'), (2, '12小时')], db_comment='raceTime比赛时间', default=1, null=True, verbose_name='比赛时间'),
        ),
    ]
