# Generated by Django 4.2.3 on 2023-08-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_tcsearch_gender_alter_tcsearch_paixu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcsearch',
            name='menOneTwos',
            field=models.ManyToManyField(to='app1.tconetwo', verbose_name='两门'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='paiXu',
            field=models.SmallIntegerField(blank=True, choices=[(3, '利润'), (2, '开始时间'), (4, 'ROI'), (1, '存在时间')], default=1, null=True, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='profitRangeBig',
            field=models.CharField(blank=True, db_comment='利润范围最大值', default=0, max_length=255, null=True, verbose_name='利润最大'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='profitRangeLittle',
            field=models.CharField(blank=True, db_comment='利润范围最小值', default=0, max_length=255, null=True, verbose_name='利润最小'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='raceTime',
            field=models.SmallIntegerField(blank=True, choices=[(3, '16小时'), (2, '12小时'), (4, '1天'), (6, '1周'), (5, '2天'), (1, '任何时间'), (7, '4周2天')], db_comment='raceTime比赛时间', default=1, null=True, verbose_name='比赛时间'),
        ),
    ]
