# Generated by Django 4.2.3 on 2023-08-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_dengluinfo_webinfo_alter_tcsearch_paixu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dengluinfo',
            name='cookie',
            field=models.CharField(blank=True, db_comment='获得的cookie信息', max_length=50, null=True, verbose_name='cookie'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(2, '女'), (1, '男')], default=1, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='paiXu',
            field=models.SmallIntegerField(blank=True, choices=[(1, '存在时间'), (2, '开始时间'), (3, '利润'), (4, 'ROI')], default=1, null=True, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='raceTime',
            field=models.CharField(blank=True, choices=[('86400', '2天'), ('186400', '4周2天'), ('86400', '1天'), ('48000', '16小时'), ('86400', '12小时'), ('86400', '1周')], db_comment='raceTime比赛时间', default='86400', max_length=50, null=True, verbose_name='比赛时间'),
        ),
        migrations.AlterField(
            model_name='tcsport',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(2, '电竞类'), (1, '体育类')], db_comment=' 比赛类型', default=1, null=True, verbose_name='比赛类型'),
        ),
    ]
