# Generated by Django 4.2.3 on 2023-08-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_dengluinfo_cookie_alter_tcsearch_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dengluinfo',
            name='cookie',
            field=models.TextField(blank=True, db_comment='获得的cookie信息', max_length=250, null=True, verbose_name='cookie'),
        ),
        migrations.AlterField(
            model_name='dengluinfo',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(2, 'post'), (1, '普通post')], db_comment=' 普通post', default=1, null=True, verbose_name='普通post'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='paiXu',
            field=models.SmallIntegerField(blank=True, choices=[(4, 'ROI'), (2, '开始时间'), (3, '利润'), (1, '存在时间')], default=1, null=True, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='raceTime',
            field=models.CharField(blank=True, choices=[('86400', '12小时'), ('86400', '1天'), ('48000', '16小时'), ('86400', '1周'), ('86400', '2天'), ('186400', '4周2天')], db_comment='raceTime比赛时间', default='86400', max_length=50, null=True, verbose_name='比赛时间'),
        ),
    ]
