# Generated by Django 4.2.3 on 2023-08-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_dengluinfo_cookie_alter_dengluinfo_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dengluinfo',
            name='cookie',
            field=models.TextField(blank=True, db_comment='获得的cookie信息', null=True, verbose_name='cookie'),
        ),
        migrations.AlterField(
            model_name='dengluinfo',
            name='token',
            field=models.CharField(blank=True, db_comment='获得的token信息', max_length=200, null=True, verbose_name='token'),
        ),
        migrations.AlterField(
            model_name='dengluinfo',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(1, '普通post'), (2, 'post')], db_comment=' 普通post', default=1, null=True, verbose_name='普通post'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(1, '男'), (2, '女')], default=1, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='paiXu',
            field=models.SmallIntegerField(blank=True, choices=[(3, '利润'), (4, 'ROI'), (1, '存在时间'), (2, '开始时间')], default=1, null=True, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='raceTime',
            field=models.CharField(blank=True, choices=[('86400', '2天'), ('48000', '16小时'), ('86400', '12小时'), ('86400', '1天'), ('86400', '1周'), ('186400', '4周2天')], db_comment='raceTime比赛时间', default='86400', max_length=50, null=True, verbose_name='比赛时间'),
        ),
        migrations.AlterField(
            model_name='webinfo',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(1, '企业站'), (2, '功能站')], db_comment=' 类型', default=1, null=True, verbose_name='类型'),
        ),
    ]
