# Generated by Django 4.2.3 on 2023-09-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_dengluinfo_authenticity_token_alter_tcsearch_paixu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcsearch',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(2, '女'), (1, '男')], default=1, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='paiXu',
            field=models.SmallIntegerField(blank=True, choices=[(1, '存在时间'), (3, '利润'), (4, 'ROI'), (2, '开始时间')], default=1, null=True, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='raceTime',
            field=models.CharField(blank=True, choices=[('172800', '2天'), ('604800', '1周'), ('43200', '12小时'), ('57600', '16小时'), ('86400', '1天')], db_comment='raceTime比赛时间', default='86400', max_length=50, null=True, verbose_name='比赛时间'),
        ),
    ]
