# Generated by Django 4.2.3 on 2023-09-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_alter_tcsearch_gender_alter_tcsearch_paixu_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_quantify1',
            options={'verbose_name': '量化方案一'},
        ),
        migrations.AlterField(
            model_name='t_quantify1',
            name='TRADE_TOKEN_ADDRESS',
            field=models.CharField(blank=True, db_comment='代币地址', default='0x768a62a22b187EB350637e720ebC552D905c0331', max_length=255, null=True, verbose_name='代币地址'),
        ),
        migrations.AlterField(
            model_name='t_quantify1',
            name='sellPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='出售价格'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='paiXu',
            field=models.SmallIntegerField(blank=True, choices=[(4, 'ROI'), (1, '存在时间'), (2, '开始时间'), (3, '利润')], default=1, null=True, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='raceTime',
            field=models.CharField(blank=True, choices=[('604800', '1周'), ('43200', '12小时'), ('57600', '16小时'), ('86400', '1天'), ('172800', '2天')], db_comment='raceTime比赛时间', default='86400', max_length=50, null=True, verbose_name='比赛时间'),
        ),
        migrations.AlterField(
            model_name='webinfo',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(2, '功能站'), (1, '企业站')], db_comment=' 类型', default=1, null=True, verbose_name='类型'),
        ),
    ]
