# Generated by Django 4.2.3 on 2023-09-24 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0026_alter_dengluinfo_type_alter_t_quantify1_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dengluinfo',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(1, '普通post'), (2, 'post')], db_comment=' 普通post', default=1, null=True, verbose_name='普通post'),
        ),
        migrations.AlterField(
            model_name='t_tokenaddr',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '停止')], db_comment='0 停止,正常', default=1),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='paiXu',
            field=models.SmallIntegerField(blank=True, choices=[(2, '开始时间'), (3, '利润'), (1, '存在时间'), (4, 'ROI')], default=1, null=True, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='raceTime',
            field=models.CharField(blank=True, choices=[('86400', '1天'), ('43200', '12小时'), ('172800', '2天'), ('57600', '16小时'), ('604800', '1周')], db_comment='raceTime比赛时间', default='86400', max_length=50, null=True, verbose_name='比赛时间'),
        ),
        migrations.AlterField(
            model_name='tcsport',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(1, '体育类'), (2, '电竞类')], db_comment=' 比赛类型', default=1, null=True, verbose_name='比赛类型'),
        ),
        migrations.AlterField(
            model_name='webinfo',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(1, '企业站'), (2, '功能站')], db_comment=' 类型', default=1, null=True, verbose_name='类型'),
        ),
        migrations.CreateModel(
            name='T_trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeToken', models.CharField(blank=True, db_comment='交易者钱包', max_length=255, null=True, verbose_name='交易者钱包')),
                ('TOKEN_ADDRESS', models.CharField(blank=True, db_comment='代币地址', max_length=255, null=True, verbose_name='代币地址')),
                ('taskId', models.CharField(blank=True, db_comment='taskId', max_length=255, null=True, verbose_name='taskId')),
                ('tradeStatus', models.IntegerField(choices=[(0, '买'), (1, '卖')], db_comment='交易状态', default=1, verbose_name='0 停止,正常')),
                ('Price', models.DecimalField(blank=True, db_comment='交易价格', decimal_places=4, max_digits=6, null=True, verbose_name='交易价格')),
                ('tradeAmount', models.DecimalField(blank=True, db_comment='交易量', decimal_places=4, max_digits=6, null=True, verbose_name='交易量')),
                ('status', models.IntegerField(choices=[(1, '正常'), (0, '停止')], db_comment='0 停止,正常', default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='修改时间')),
                ('QuantifyId', models.IntegerField(blank=True, db_comment='量化Id', default=0, null=True, verbose_name='量化Id')),
                ('taskRemark', models.CharField(blank=True, db_comment='task备注', max_length=255, null=True, verbose_name='task备注')),
                ('uid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '交易表',
                'db_table': 'T_trade',
                'db_table_comment': '交易表',
            },
        ),
        migrations.CreateModel(
            name='T_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskId', models.CharField(blank=True, db_comment='taskId', max_length=255, null=True, verbose_name='taskId')),
                ('status', models.IntegerField(choices=[(1, '正常'), (0, '停止')], db_comment='0 停止,正常', default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='修改时间')),
                ('QuantifyId', models.IntegerField(blank=True, db_comment='量化Id', default=0, null=True, verbose_name='量化Id')),
                ('taskRemark', models.CharField(blank=True, db_comment='task备注', max_length=255, null=True, verbose_name='task备注')),
                ('uid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'task地址',
                'db_table': 'T_task',
                'db_table_comment': 'task地址',
            },
        ),
    ]
