# Generated by Django 4.2.3 on 2023-09-29 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0030_alter_t_quantify1_uid_alter_t_task_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_quantify1',
            name='status',
            field=models.IntegerField(choices=[(1, '运行'), (0, '关闭')], db_comment='0 关闭,1运行中', default=0),
        ),
        migrations.AlterField(
            model_name='t_task',
            name='status',
            field=models.IntegerField(choices=[(0, '停止'), (1, '正常')], db_comment='0 停止,正常', default=1),
        ),
        migrations.AlterField(
            model_name='t_tokenaddr',
            name='status',
            field=models.IntegerField(choices=[(0, '停止'), (1, '正常')], db_comment='0 停止,正常', default=1),
        ),
        migrations.AlterField(
            model_name='t_trade',
            name='status',
            field=models.IntegerField(choices=[(0, '停止'), (1, '正常')], db_comment='0 停止,正常', default=1),
        ),
        migrations.AlterField(
            model_name='t_trade',
            name='tradeStatus',
            field=models.IntegerField(choices=[(0, '买'), (1, '卖')], db_comment='交易状态', default=1, verbose_name='0 停止,正常'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(2, '女'), (1, '男')], default=1, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='paiXu',
            field=models.SmallIntegerField(blank=True, choices=[(1, '存在时间'), (4, 'ROI'), (2, '开始时间'), (3, '利润')], default=1, null=True, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='raceTime',
            field=models.CharField(blank=True, choices=[('172800', '2天'), ('43200', '12小时'), ('57600', '16小时'), ('604800', '1周'), ('86400', '1天')], db_comment='raceTime比赛时间', default='86400', max_length=50, null=True, verbose_name='比赛时间'),
        ),
        migrations.AlterField(
            model_name='tcsport',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(1, '体育类'), (2, '电竞类')], db_comment=' 比赛类型', default=1, null=True, verbose_name='比赛类型'),
        ),
        migrations.CreateModel(
            name='T_TokenAddrBak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TOKEN_ADDRESS', models.CharField(blank=True, db_comment='代币地址', max_length=255, null=True, verbose_name='代币地址')),
                ('TOKEN_private', models.CharField(blank=True, db_comment='private', max_length=255, null=True, verbose_name='private')),
                ('TOKEN_public', models.CharField(blank=True, db_comment='public', max_length=255, null=True, verbose_name='public')),
                ('TOKEN_bak', models.CharField(blank=True, db_comment='中文备注', max_length=255, null=True, verbose_name='中文备注')),
                ('status', models.IntegerField(choices=[(0, '停止'), (1, '正常')], db_comment='0 停止,正常', default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='修改时间')),
                ('QuantifyId', models.IntegerField(blank=True, db_comment='量化Id', default=0, null=True, verbose_name='量化Id')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'T_TokenAddrBak地址',
                'db_table': 'T_TokenAddrBak',
                'db_table_comment': 'T_TokenAddrBak地址',
            },
        ),
    ]
