# Generated by Django 4.2.3 on 2023-09-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_alter_t_quantify1_status_alter_t_task_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_quantify1',
            options={'verbose_name_plural': '设置量化'},
        ),
        migrations.AlterModelOptions(
            name='t_task',
            options={'verbose_name_plural': '启动中量化'},
        ),
        migrations.AlterModelOptions(
            name='t_tokenaddr',
            options={'verbose_name_plural': '我的钱包'},
        ),
        migrations.AlterModelOptions(
            name='t_trade',
            options={'verbose_name_plural': '交易表'},
        ),
        migrations.AlterModelTableComment(
            name='t_quantify1',
            table_comment='设置量化',
        ),
        migrations.AlterModelTableComment(
            name='t_task',
            table_comment='启动中量化',
        ),
        migrations.AlterModelTableComment(
            name='t_tokenaddr',
            table_comment='我的钱包',
        ),
        migrations.AlterField(
            model_name='dengluinfo',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(2, 'post'), (1, '普通post')], db_comment=' 普通post', default=1, null=True, verbose_name='普通post'),
        ),
        migrations.AlterField(
            model_name='t_quantify1',
            name='AmountBuy0',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='购买区间0'),
        ),
        migrations.AlterField(
            model_name='t_quantify1',
            name='AmountBuy1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='购买区间1'),
        ),
        migrations.AlterField(
            model_name='t_quantify1',
            name='AmountSell0',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='销售区间0'),
        ),
        migrations.AlterField(
            model_name='t_quantify1',
            name='AmountSell1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='销售区间1'),
        ),
        migrations.AlterField(
            model_name='t_quantify1',
            name='PercentBuy',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='下调 百分比'),
        ),
        migrations.AlterField(
            model_name='t_quantify1',
            name='PercenttSell',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='上调 百分比'),
        ),
        migrations.AlterField(
            model_name='t_quantify1',
            name='buyPrice',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='购买价格'),
        ),
        migrations.AlterField(
            model_name='t_quantify1',
            name='coinsRecharge',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='不足充币'),
        ),
        migrations.AlterField(
            model_name='t_quantify1',
            name='sellPrice',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='出售价格'),
        ),
        migrations.AlterField(
            model_name='t_quantify1',
            name='status',
            field=models.IntegerField(choices=[(0, '关闭'), (1, '运行')], db_comment='0 关闭,1运行中', default=0),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='paiXu',
            field=models.SmallIntegerField(blank=True, choices=[(4, 'ROI'), (2, '开始时间'), (3, '利润'), (1, '存在时间')], default=1, null=True, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='raceTime',
            field=models.CharField(blank=True, choices=[('604800', '1周'), ('172800', '2天'), ('57600', '16小时'), ('86400', '1天'), ('43200', '12小时')], db_comment='raceTime比赛时间', default='86400', max_length=50, null=True, verbose_name='比赛时间'),
        ),
        migrations.AlterField(
            model_name='tcsport',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(2, '电竞类'), (1, '体育类')], db_comment=' 比赛类型', default=1, null=True, verbose_name='比赛类型'),
        ),
        migrations.AlterField(
            model_name='webinfo',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(2, '功能站'), (1, '企业站')], db_comment=' 类型', default=1, null=True, verbose_name='类型'),
        ),
    ]
