# Generated by Django 4.2.3 on 2023-10-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_t_trade_tradehash_alter_dengluinfo_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dengluinfo',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(2, 'post'), (1, '普通post')], db_comment=' 普通post', default=1, null=True, verbose_name='普通post'),
        ),
        migrations.AlterField(
            model_name='t_quantify1',
            name='status',
            field=models.IntegerField(choices=[(1, '运行'), (0, '关闭')], db_comment='0 关闭,1运行中', default=0),
        ),
        migrations.AlterField(
            model_name='t_trade',
            name='tradeAmount',
            field=models.BigIntegerField(blank=True, db_comment='交易量', null=True, verbose_name='交易量'),
        ),
        migrations.AlterField(
            model_name='t_trade',
            name='tradeStatus',
            field=models.IntegerField(choices=[(1, '卖'), (2, 'Approved'), (0, '买')], db_comment='交易状态', default=1, verbose_name='0 停止,正常'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='paiXu',
            field=models.SmallIntegerField(blank=True, choices=[(2, '开始时间'), (1, '存在时间'), (3, '利润'), (4, 'ROI')], default=1, null=True, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='raceTime',
            field=models.CharField(blank=True, choices=[('57600', '16小时'), ('604800', '1周'), ('86400', '1天'), ('43200', '12小时'), ('172800', '2天')], db_comment='raceTime比赛时间', default='86400', max_length=50, null=True, verbose_name='比赛时间'),
        ),
    ]
