# Generated by Django 4.2.3 on 2023-10-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_alter_t_task_options_alter_t_task_table_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_tokenaddr',
            name='TOKEN_price',
            field=models.CharField(blank=True, db_comment='代币余额', max_length=255, null=True, verbose_name='代币余额'),
        ),
        migrations.AlterField(
            model_name='t_quantify1',
            name='status',
            field=models.IntegerField(choices=[(0, '关闭'), (1, '运行')], db_comment='0 关闭,1运行中', default=0),
        ),
        migrations.AlterField(
            model_name='t_trade',
            name='tradeStatus',
            field=models.IntegerField(choices=[(1, '卖'), (2, 'Approved'), (0, '买')], db_comment='交易状态', default=1, verbose_name='0 停止,正常'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='paiXu',
            field=models.SmallIntegerField(blank=True, choices=[(4, 'ROI'), (2, '开始时间'), (1, '存在时间'), (3, '利润')], default=1, null=True, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='raceTime',
            field=models.CharField(blank=True, choices=[('43200', '12小时'), ('86400', '1天'), ('57600', '16小时'), ('172800', '2天'), ('604800', '1周')], db_comment='raceTime比赛时间', default='86400', max_length=50, null=True, verbose_name='比赛时间'),
        ),
        migrations.AlterField(
            model_name='tcsport',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(1, '体育类'), (2, '电竞类')], db_comment=' 比赛类型', default=1, null=True, verbose_name='比赛类型'),
        ),
    ]
