# Generated by Django 4.2.3 on 2023-10-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_t_tokenaddr_token_price_alter_t_quantify1_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_quantify1',
            name='DlBuyNumber',
            field=models.IntegerField(blank=True, db_comment='购买数量', default=0, null=True, verbose_name='购买数量'),
        ),
        migrations.AddField(
            model_name='t_quantify1',
            name='DlBuyTOKEN_price',
            field=models.CharField(blank=True, db_comment='购买价格', max_length=255, null=True, verbose_name='购买价格'),
        ),
        migrations.AddField(
            model_name='t_quantify1',
            name='DlSellNumber',
            field=models.IntegerField(blank=True, db_comment='出售数量', default=0, null=True, verbose_name='出售数量'),
        ),
        migrations.AddField(
            model_name='t_quantify1',
            name='DlSellTOKEN_price',
            field=models.CharField(blank=True, db_comment='出售价格', max_length=255, null=True, verbose_name='出售价格'),
        ),
        migrations.AddField(
            model_name='t_quantify1',
            name='DlTOKEN_ADDRESS',
            field=models.CharField(blank=True, db_comment='独立地址', max_length=255, null=True, verbose_name='独立地址'),
        ),
        migrations.AddField(
            model_name='t_quantify1',
            name='DlTOKEN_private',
            field=models.CharField(blank=True, db_comment='private', max_length=255, null=True, verbose_name='private'),
        ),
        migrations.AddField(
            model_name='t_quantify1',
            name='Dlprice_status',
            field=models.IntegerField(choices=[(1, '独立'), (0, '全局')], db_comment='0 全局,1独立', default=0),
        ),
        migrations.AlterField(
            model_name='t_quantify1',
            name='status',
            field=models.IntegerField(choices=[(1, '运行'), (0, '关闭')], db_comment='0 关闭,1运行中', default=0),
        ),
        migrations.AlterField(
            model_name='t_trade',
            name='tradeStatus',
            field=models.IntegerField(choices=[(1, '卖'), (0, '买'), (2, 'Approved')], db_comment='交易状态', default=1, verbose_name='0 停止,正常'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(1, '男'), (2, '女')], default=1, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='paiXu',
            field=models.SmallIntegerField(blank=True, choices=[(2, '开始时间'), (4, 'ROI'), (1, '存在时间'), (3, '利润')], default=1, null=True, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='raceTime',
            field=models.CharField(blank=True, choices=[('57600', '16小时'), ('86400', '1天'), ('604800', '1周'), ('43200', '12小时'), ('172800', '2天')], db_comment='raceTime比赛时间', default='86400', max_length=50, null=True, verbose_name='比赛时间'),
        ),
        migrations.AlterField(
            model_name='webinfo',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(1, '企业站'), (2, '功能站')], db_comment=' 类型', default=1, null=True, verbose_name='类型'),
        ),
    ]
