# Generated by Django 4.2.3 on 2023-10-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0043_rename_dlbuynumber_t_tokenaddr_buynumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_quantify1',
            name='duration',
            field=models.DurationField(blank=True, help_text='开始后多少秒结束.', null=True),
        ),
        migrations.AddField(
            model_name='t_quantify1',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='结束时间.', null=True),
        ),
        migrations.AddField(
            model_name='t_quantify1',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='开始时间.', null=True),
        ),
        migrations.AddField(
            model_name='t_trade',
            name='statusTip',
            field=models.IntegerField(choices=[(1, '已收取'), (0, '未收取')], db_comment='0 未收取,1 已收取', default=0, verbose_name='小费'),
        ),
        migrations.AddField(
            model_name='t_trade',
            name='tipNumber',
            field=models.CharField(blank=True, db_comment='小费值', max_length=255, null=True, verbose_name='小费值'),
        ),
        migrations.AlterField(
            model_name='t_quantify1',
            name='sellPrice',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='出售价格-选择独立Token后不起作用'),
        ),
        migrations.AlterField(
            model_name='t_task',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '停止')], db_comment='0 停止,正常', default=1),
        ),
        migrations.AlterField(
            model_name='t_tokenaddr',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '停止')], db_comment='0 停止,正常', default=1),
        ),
        migrations.AlterField(
            model_name='t_tokenaddrbak',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '停止')], db_comment='0 停止,正常', default=1),
        ),
        migrations.AlterField(
            model_name='t_trade',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '停止')], db_comment='0 停止,正常', default=1),
        ),
        migrations.AlterField(
            model_name='t_trade',
            name='tradeStatus',
            field=models.IntegerField(choices=[(0, '买'), (2, 'Approved'), (1, '卖')], db_comment='交易状态', default=1, verbose_name='0 停止,正常'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(1, '男'), (2, '女')], default=1, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='paiXu',
            field=models.SmallIntegerField(blank=True, choices=[(1, '存在时间'), (3, '利润'), (4, 'ROI'), (2, '开始时间')], default=1, null=True, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='raceTime',
            field=models.CharField(blank=True, choices=[('43200', '12小时'), ('57600', '16小时'), ('604800', '1周'), ('172800', '2天'), ('86400', '1天')], db_comment='raceTime比赛时间', default='86400', max_length=50, null=True, verbose_name='比赛时间'),
        ),
    ]
