# Generated by Django 4.2.3 on 2023-11-01 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0048_alter_dengluinfo_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorytoken',
            options={'verbose_name_plural': '地址分类'},
        ),
        migrations.AlterModelTableComment(
            name='categorytoken',
            table_comment='地址分类',
        ),
        migrations.AddField(
            model_name='t_tokenaddr',
            name='TOKEN_otherPrice',
            field=models.CharField(blank=True, db_comment='代币余额', max_length=255, null=True, verbose_name='代币余额'),
        ),
        migrations.AlterField(
            model_name='categorytoken',
            name='uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dengluinfo',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(2, 'post'), (1, '普通post')], db_comment=' 普通post', default=1, null=True, verbose_name='普通post'),
        ),
        migrations.AlterField(
            model_name='t_quantify1',
            name='Dlprice_status',
            field=models.IntegerField(choices=[(0, '全局'), (1, '独立')], db_comment='0 全局,1独立', default=0),
        ),
        migrations.AlterField(
            model_name='t_quantify1',
            name='status',
            field=models.IntegerField(choices=[(0, '关闭'), (1, '运行')], db_comment='0 关闭,1运行中', default=0),
        ),
        migrations.AlterField(
            model_name='t_tokenaddr',
            name='TOKEN_price',
            field=models.CharField(blank=True, db_comment='bnb余额', max_length=255, null=True, verbose_name='bnb余额'),
        ),
        migrations.AlterField(
            model_name='t_trade',
            name='statusTip',
            field=models.IntegerField(choices=[(1, '已收取'), (0, '未收取')], db_comment='0 未收取,1 已收取', default=0, verbose_name='小费'),
        ),
        migrations.AlterField(
            model_name='t_trade',
            name='tradeStatus',
            field=models.IntegerField(choices=[(0, '买'), (2, 'Approved'), (1, '卖')], db_comment='交易状态', default=1, verbose_name='0 停止,正常'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='paiXu',
            field=models.SmallIntegerField(blank=True, choices=[(2, '开始时间'), (3, '利润'), (1, '存在时间'), (4, 'ROI')], default=1, null=True, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='raceTime',
            field=models.CharField(blank=True, choices=[('604800', '1周'), ('172800', '2天'), ('43200', '12小时'), ('57600', '16小时'), ('86400', '1天')], db_comment='raceTime比赛时间', default='86400', max_length=50, null=True, verbose_name='比赛时间'),
        ),
    ]
