# Generated by Django 4.2.3 on 2023-11-01 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0049_alter_categorytoken_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_tokenaddrbak',
            name='BuyNumber',
            field=models.IntegerField(blank=True, db_comment='购买数量', default=0, null=True, verbose_name='购买数量'),
        ),
        migrations.AddField(
            model_name='t_tokenaddrbak',
            name='BuyTOKEN_price',
            field=models.CharField(blank=True, db_comment='购买价格', max_length=255, null=True, verbose_name='购买价格'),
        ),
        migrations.AddField(
            model_name='t_tokenaddrbak',
            name='SellNumber',
            field=models.IntegerField(blank=True, db_comment='出售数量', default=0, null=True, verbose_name='出售数量'),
        ),
        migrations.AddField(
            model_name='t_tokenaddrbak',
            name='SellTOKEN_price',
            field=models.CharField(blank=True, db_comment='出售价格', max_length=255, null=True, verbose_name='出售价格'),
        ),
        migrations.AddField(
            model_name='t_tokenaddrbak',
            name='TOKEN_otherPrice',
            field=models.CharField(blank=True, db_comment='代币余额', max_length=255, null=True, verbose_name='代币余额'),
        ),
        migrations.AddField(
            model_name='t_tokenaddrbak',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.categorytoken'),
        ),
        migrations.AlterField(
            model_name='t_quantify1',
            name='Dlprice_status',
            field=models.IntegerField(choices=[(1, '独立'), (0, '全局')], db_comment='0 全局,1独立', default=0),
        ),
        migrations.AlterField(
            model_name='t_task',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '停止')], db_comment='0 停止,正常', default=1),
        ),
        migrations.AlterField(
            model_name='t_tokenaddr',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '停止')], db_comment='0 停止,正常', default=1),
        ),
        migrations.AlterField(
            model_name='t_tokenaddrbak',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '停止')], db_comment='0 停止,正常', default=1),
        ),
        migrations.AlterField(
            model_name='t_trade',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '停止')], db_comment='0 停止,正常', default=1),
        ),
        migrations.AlterField(
            model_name='t_trade',
            name='tradeStatus',
            field=models.IntegerField(choices=[(2, 'Approved'), (0, '买'), (1, '卖')], db_comment='交易状态', default=1, verbose_name='0 停止,正常'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='paiXu',
            field=models.SmallIntegerField(blank=True, choices=[(1, '存在时间'), (2, '开始时间'), (4, 'ROI'), (3, '利润')], default=1, null=True, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='raceTime',
            field=models.CharField(blank=True, choices=[('86400', '1天'), ('172800', '2天'), ('604800', '1周'), ('43200', '12小时'), ('57600', '16小时')], db_comment='raceTime比赛时间', default='86400', max_length=50, null=True, verbose_name='比赛时间'),
        ),
    ]
