# Generated by Django 4.2.3 on 2023-11-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0052_alter_dengluinfo_type_alter_t_task_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorytoken',
            options={'verbose_name_plural': 'Token分类'},
        ),
        migrations.AlterModelTableComment(
            name='categorytoken',
            table_comment='Token分类',
        ),
        migrations.AlterField(
            model_name='t_quantify1',
            name='status',
            field=models.IntegerField(choices=[(0, '关闭'), (1, '运行')], db_comment='0 关闭,1运行中', default=0),
        ),
        migrations.AlterField(
            model_name='t_task',
            name='status',
            field=models.IntegerField(choices=[(0, '停止'), (1, '正常')], db_comment='0 停止,正常', default=1),
        ),
        migrations.AlterField(
            model_name='t_tokenaddr',
            name='status',
            field=models.IntegerField(choices=[(0, '停止'), (1, '正常')], db_comment='0 停止,正常', default=1),
        ),
        migrations.AlterField(
            model_name='t_tokenaddrbak',
            name='status',
            field=models.IntegerField(choices=[(0, '停止'), (1, '正常')], db_comment='0 停止,正常', default=1),
        ),
        migrations.AlterField(
            model_name='t_trade',
            name='status',
            field=models.IntegerField(choices=[(0, '停止'), (1, '正常')], db_comment='0 停止,正常', default=1),
        ),
        migrations.AlterField(
            model_name='t_trade',
            name='statusTip',
            field=models.IntegerField(choices=[(0, '未收取'), (1, '已收取')], db_comment='0 未收取,1 已收取', default=0, verbose_name='小费'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='paiXu',
            field=models.SmallIntegerField(blank=True, choices=[(1, '存在时间'), (2, '开始时间'), (3, '利润'), (4, 'ROI')], default=1, null=True, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='tcsearch',
            name='raceTime',
            field=models.CharField(blank=True, choices=[('43200', '12小时'), ('57600', '16小时'), ('86400', '1天'), ('172800', '2天'), ('604800', '1周')], db_comment='raceTime比赛时间', default='86400', max_length=50, null=True, verbose_name='比赛时间'),
        ),
        migrations.AlterField(
            model_name='webinfo',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(1, '企业站'), (2, '功能站')], db_comment=' 类型', default=1, null=True, verbose_name='类型'),
        ),
        migrations.AlterModelTable(
            name='categorytoken',
            table='T_CategoryToken',
        ),
    ]
