# Generated by Django 4.2.3 on 2023-11-03 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0053_alter_categorytoken_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_tokenaddr',
            name='category',
        ),
    ]
