# Generated by Django 4.2.3 on 2023-11-03 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0054_remove_t_tokenaddr_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_tokenaddr',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.categorytoken'),
        ),
    ]
