# Generated by Django 4.2.3 on 2023-11-03 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0055_t_tokenaddr_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_tokenaddrbak',
            name='category',
        ),
    ]
