# Generated by Django 4.2.3 on 2023-11-03 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0056_remove_t_tokenaddrbak_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_tokenaddrbak',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.categorytoken'),
        ),
    ]
