# Generated by Django 4.2.3 on 2024-03-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0057_t_tokenaddrbak_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcweb',
            name='Str1',
            field=models.CharField(blank=True, db_comment='str', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tcweb',
            name='Str10',
            field=models.CharField(blank=True, db_comment='str', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tcweb',
            name='Str2',
            field=models.CharField(blank=True, db_comment='str', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tcweb',
            name='Str3',
            field=models.CharField(blank=True, db_comment='str', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tcweb',
            name='Str4',
            field=models.CharField(blank=True, db_comment='str', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tcweb',
            name='Str5',
            field=models.CharField(blank=True, db_comment='str', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tcweb',
            name='Str6',
            field=models.CharField(blank=True, db_comment='str', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tcweb',
            name='Str7',
            field=models.CharField(blank=True, db_comment='str', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tcweb',
            name='Str8',
            field=models.CharField(blank=True, db_comment='str', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tcweb',
            name='Str9',
            field=models.CharField(blank=True, db_comment='str', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tcweb',
            name='number1',
            field=models.IntegerField(blank=True, db_comment='number1', default=1, null=True),
        ),
        migrations.AddField(
            model_name='tcweb',
            name='number10',
            field=models.IntegerField(blank=True, db_comment='number1', default=1, null=True),
        ),
        migrations.AddField(
            model_name='tcweb',
            name='number11',
            field=models.IntegerField(blank=True, db_comment='number1', default=1, null=True),
        ),
        migrations.AddField(
            model_name='tcweb',
            name='number2',
            field=models.IntegerField(blank=True, db_comment='number1', default=1, null=True),
        ),
        migrations.AddField(
            model_name='tcweb',
            name='number3',
            field=models.IntegerField(blank=True, db_comment='number1', default=1, null=True),
        ),
        migrations.AddField(
            model_name='tcweb',
            name='number4',
            field=models.IntegerField(blank=True, db_comment='number1', default=1, null=True),
        ),
        migrations.AddField(
            model_name='tcweb',
            name='number5',
            field=models.IntegerField(blank=True, db_comment='number1', default=1, null=True),
        ),
        migrations.AddField(
            model_name='tcweb',
            name='number6',
            field=models.IntegerField(blank=True, db_comment='number1', default=1, null=True),
        ),
        migrations.AddField(
            model_name='tcweb',
            name='number7',
            field=models.IntegerField(blank=True, db_comment='number1', default=1, null=True),
        ),
        migrations.AddField(
            model_name='tcweb',
            name='number8',
            field=models.IntegerField(blank=True, db_comment='number1', default=1, null=True),
        ),
        migrations.AddField(
            model_name='tcweb',
            name='number9',
            field=models.IntegerField(blank=True, db_comment='number1', default=1, null=True),
        ),
    ]
