# Generated by Django 4.2.3 on 2024-03-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0058_tcweb_str1_tcweb_str10_tcweb_str2_tcweb_str3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcweb',
            name='Str1',
        ),
        migrations.RemoveField(
            model_name='tcweb',
            name='Str10',
        ),
        migrations.RemoveField(
            model_name='tcweb',
            name='Str2',
        ),
        migrations.RemoveField(
            model_name='tcweb',
            name='Str3',
        ),
        migrations.RemoveField(
            model_name='tcweb',
            name='Str4',
        ),
        migrations.RemoveField(
            model_name='tcweb',
            name='Str5',
        ),
        migrations.RemoveField(
            model_name='tcweb',
            name='Str6',
        ),
        migrations.RemoveField(
            model_name='tcweb',
            name='Str7',
        ),
        migrations.RemoveField(
            model_name='tcweb',
            name='Str8',
        ),
        migrations.RemoveField(
            model_name='tcweb',
            name='Str9',
        ),
        migrations.RemoveField(
            model_name='tcweb',
            name='number1',
        ),
        migrations.RemoveField(
            model_name='tcweb',
            name='number10',
        ),
        migrations.RemoveField(
            model_name='tcweb',
            name='number11',
        ),
        migrations.RemoveField(
            model_name='tcweb',
            name='number2',
        ),
        migrations.RemoveField(
            model_name='tcweb',
            name='number3',
        ),
        migrations.RemoveField(
            model_name='tcweb',
            name='number4',
        ),
        migrations.RemoveField(
            model_name='tcweb',
            name='number5',
        ),
        migrations.RemoveField(
            model_name='tcweb',
            name='number6',
        ),
        migrations.RemoveField(
            model_name='tcweb',
            name='number7',
        ),
        migrations.RemoveField(
            model_name='tcweb',
            name='number8',
        ),
        migrations.RemoveField(
            model_name='tcweb',
            name='number9',
        ),
        migrations.AddField(
            model_name='webinfo',
            name='Str1',
            field=models.CharField(blank=True, db_comment='str', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webinfo',
            name='Str10',
            field=models.CharField(blank=True, db_comment='str', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webinfo',
            name='Str2',
            field=models.CharField(blank=True, db_comment='str', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webinfo',
            name='Str3',
            field=models.CharField(blank=True, db_comment='str', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webinfo',
            name='Str4',
            field=models.CharField(blank=True, db_comment='str', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webinfo',
            name='Str5',
            field=models.CharField(blank=True, db_comment='str', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webinfo',
            name='Str6',
            field=models.CharField(blank=True, db_comment='str', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webinfo',
            name='Str7',
            field=models.CharField(blank=True, db_comment='str', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webinfo',
            name='Str8',
            field=models.CharField(blank=True, db_comment='str', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webinfo',
            name='Str9',
            field=models.CharField(blank=True, db_comment='str', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webinfo',
            name='number1',
            field=models.IntegerField(blank=True, db_comment='number1', default=1, null=True),
        ),
        migrations.AddField(
            model_name='webinfo',
            name='number10',
            field=models.IntegerField(blank=True, db_comment='number1', default=1, null=True),
        ),
        migrations.AddField(
            model_name='webinfo',
            name='number11',
            field=models.IntegerField(blank=True, db_comment='number1', default=1, null=True),
        ),
        migrations.AddField(
            model_name='webinfo',
            name='number2',
            field=models.IntegerField(blank=True, db_comment='number1', default=1, null=True),
        ),
        migrations.AddField(
            model_name='webinfo',
            name='number3',
            field=models.IntegerField(blank=True, db_comment='number1', default=1, null=True),
        ),
        migrations.AddField(
            model_name='webinfo',
            name='number4',
            field=models.IntegerField(blank=True, db_comment='number1', default=1, null=True),
        ),
        migrations.AddField(
            model_name='webinfo',
            name='number5',
            field=models.IntegerField(blank=True, db_comment='number1', default=1, null=True),
        ),
        migrations.AddField(
            model_name='webinfo',
            name='number6',
            field=models.IntegerField(blank=True, db_comment='number1', default=1, null=True),
        ),
        migrations.AddField(
            model_name='webinfo',
            name='number7',
            field=models.IntegerField(blank=True, db_comment='number1', default=1, null=True),
        ),
        migrations.AddField(
            model_name='webinfo',
            name='number8',
            field=models.IntegerField(blank=True, db_comment='number1', default=1, null=True),
        ),
        migrations.AddField(
            model_name='webinfo',
            name='number9',
            field=models.IntegerField(blank=True, db_comment='number1', default=1, null=True),
        ),
    ]
