# Generated by Django 4.2.3 on 2024-06-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0059_remove_tcweb_str1_remove_tcweb_str10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinfo',
            name='jiangJinChi',
            field=models.FloatField(blank=True, db_comment='奖金池', default=0, null=True, verbose_name='奖金池'),
        ),
    ]
